# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

LinvMult <- function(covarray, y, locs, NNarray) {
    .Call('_npspec_LinvMult', PACKAGE = 'npspec', covarray, y, locs, NNarray)
}

LinvTransMult <- function(covarray, z, locs, NNarray) {
    .Call('_npspec_LinvTransMult', PACKAGE = 'npspec', covarray, z, locs, NNarray)
}

vecchiaPrecond <- function(covarray, y, locs, NNarray) {
    .Call('_npspec_vecchiaPrecond', PACKAGE = 'npspec', covarray, y, locs, NNarray)
}

getLinvEntries <- function(covarray, locs, NNarray) {
    .Call('_npspec_getLinvEntries', PACKAGE = 'npspec', covarray, locs, NNarray)
}

LinvTransMultFromEntries <- function(LinvEntries, z, NNarray) {
    .Call('_npspec_LinvTransMultFromEntries', PACKAGE = 'npspec', LinvEntries, z, NNarray)
}

LinvMultFromEntries <- function(LinvEntries, z, NNarray) {
    .Call('_npspec_LinvMultFromEntries', PACKAGE = 'npspec', LinvEntries, z, NNarray)
}

vecchiaPrecondFromEntries <- function(LinvEntries, y, NNarray) {
    .Call('_npspec_vecchiaPrecondFromEntries', PACKAGE = 'npspec', LinvEntries, y, NNarray)
}

vecchiaLik <- function(covarray, y, locs, NNarray) {
    .Call('_npspec_vecchiaLik', PACKAGE = 'npspec', covarray, y, locs, NNarray)
}

